### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by wboeke** [joanrieu/synth-odyssey#1]
The directory vendor/rtmidi is empty. There should be a file CMakeLists.txt and RtMidi.h

**Comment by wboeke** [comment]
In the meantime i figured that you have to clone with option --recurse-submodules, so this issue is solved. But: next hurdle is at runtime: 
qrc:/ContextMenu.qml:2 module "QtQuick.Controls" version 2.12 is not installed
This is probably an old library. I am on Linux (Fedora). Could this project please be updated?

**Comment by joanrieu** [comment]
Please make sure you have Qt Quick Controls 2 installed. The specified version (2.12) is a minimum, newer releases are backwards-compatible without any change in the code.
